"""empty message

Revision ID: 3cf1e83c50e3
Revises: 
Create Date: 2019-10-04 21:51:17.025139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3cf1e83c50e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordenes', sa.Column('user', sa.String(length=60), nullable=False))
    op.drop_constraint('ordenes_ibfk_1', 'ordenes', type_='foreignkey')
    op.create_foreign_key(None, 'ordenes', 'usuarios', ['user'], ['username'])
    op.drop_column('ordenes', 'nro_afiliado')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordenes', sa.Column('nro_afiliado', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ordenes', type_='foreignkey')
    op.create_foreign_key('ordenes_ibfk_1', 'ordenes', 'usuarios', ['nro_afiliado'], ['nro_afiliado'])
    op.drop_column('ordenes', 'user')
    # ### end Alembic commands ###
