"""empty message

Revision ID: 8463780acf57
Revises: 
Create Date: 2019-10-04 19:36:24.453474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8463780acf57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('nro_afiliado', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('telefono', sa.String(length=60), nullable=True),
    sa.Column('ciudad', sa.String(length=60), nullable=True),
    sa.Column('estado_civil', sa.String(length=60), nullable=True),
    sa.Column('direccion', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_ciudad'), 'usuarios', ['ciudad'], unique=False)
    op.create_index(op.f('ix_usuarios_direccion'), 'usuarios', ['direccion'], unique=False)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_estado_civil'), 'usuarios', ['estado_civil'], unique=False)
    op.create_index(op.f('ix_usuarios_first_name'), 'usuarios', ['first_name'], unique=False)
    op.create_index(op.f('ix_usuarios_last_name'), 'usuarios', ['last_name'], unique=False)
    op.create_index(op.f('ix_usuarios_nro_afiliado'), 'usuarios', ['nro_afiliado'], unique=True)
    op.create_index(op.f('ix_usuarios_telefono'), 'usuarios', ['telefono'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('ordenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('estado', sa.String(length=300), nullable=True),
    sa.Column('tipo', sa.String(length=300), nullable=True),
    sa.Column('user', sa.String(length=60), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['usuarios.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordenes')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_telefono'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_nro_afiliado'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_last_name'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_first_name'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_estado_civil'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_direccion'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_ciudad'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
