"""empty message

Revision ID: d4b4f89b2001
Revises: 3cf1e83c50e3
Create Date: 2019-10-04 21:52:58.108097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4b4f89b2001'
down_revision = '3cf1e83c50e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ordenes_ibfk_1', 'ordenes', type_='foreignkey')
    op.drop_column('ordenes', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordenes', sa.Column('user', mysql.VARCHAR(length=60), nullable=False))
    op.create_foreign_key('ordenes_ibfk_1', 'ordenes', 'usuarios', ['user'], ['username'])
    # ### end Alembic commands ###
